version: "3.7"
services:
  api:
    image: golang:1.12
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - GOFLAGS=-mod=vendor
    entrypoint: "/app/scripts/dev-entrypoint.sh"
  doc:
    image: quay.io/goswagger/swagger:v0.19.0
    volumes:
      - ./api/swagger.yml:/input/swagger.yml
    ports:
      - 3001:3001
    command: serve /input/swagger.yml --port=3001 --no-open
