consumes:
- application/json
info:
  title: A payments API
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  payment:
    $ref: "payment.yml"
  payments:
    type: object
    required:
      - data
      - links
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/payment"
      links:
        type: object
        required:
          - self
        properties:
          self:
            type: string
paths:
  /payments:
    get:
      responses:
        200:
          description: list of payments
          schema:
            $ref: "#/definitions/payments"
  /payment:
    get:
      responses:
        200:
          description: a payment
          schema:
            $ref: "#/definitions/payment"
